// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/chat.proto

package org.tio.examples.im.common.packets;

/**
 * Protobuf enum {@code org.tio.examples.im.common.packets.Command}
 */
public enum Command
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>COMMAND_UNKNOW = 0;</code>
   */
  COMMAND_UNKNOW(0),
  /**
   * <pre>
   *握手请求，含http的websocket握手请求
   * </pre>
   *
   * <code>COMMAND_HANDSHAKE_REQ = 1;</code>
   */
  COMMAND_HANDSHAKE_REQ(1),
  /**
   * <pre>
   *握手响应，含http的websocket握手响应
   * </pre>
   *
   * <code>COMMAND_HANDSHAKE_RESP = 2;</code>
   */
  COMMAND_HANDSHAKE_RESP(2),
  /**
   * <pre>
   *鉴权请求
   * </pre>
   *
   * <code>COMMAND_AUTH_REQ = 3;</code>
   */
  COMMAND_AUTH_REQ(3),
  /**
   * <pre>
   * 鉴权响应
   * </pre>
   *
   * <code>COMMAND_AUTH_RESP = 4;</code>
   */
  COMMAND_AUTH_RESP(4),
  /**
   * <pre>
   *申请进入群组
   * </pre>
   *
   * <code>COMMAND_JOIN_GROUP_REQ = 5;</code>
   */
  COMMAND_JOIN_GROUP_REQ(5),
  /**
   * <pre>
   *申请进入群组响应
   * </pre>
   *
   * <code>COMMAND_JOIN_GROUP_RESP = 6;</code>
   */
  COMMAND_JOIN_GROUP_RESP(6),
  /**
   * <pre>
   *进入房间通知
   * </pre>
   *
   * <code>COMMAND_JOIN_GROUP_NOTIFY_RESP = 7;</code>
   */
  COMMAND_JOIN_GROUP_NOTIFY_RESP(7),
  /**
   * <pre>
   *聊天请求
   * </pre>
   *
   * <code>COMMAND_CHAT_REQ = 8;</code>
   */
  COMMAND_CHAT_REQ(8),
  /**
   * <pre>
   *聊天响应
   * </pre>
   *
   * <code>COMMAND_CHAT_RESP = 9;</code>
   */
  COMMAND_CHAT_RESP(9),
  /**
   * <pre>
   *开播请求
   * </pre>
   *
   * <code>COMMAND_START_SHOW_REQ = 10;</code>
   */
  COMMAND_START_SHOW_REQ(10),
  /**
   * <pre>
   *开播响应
   * </pre>
   *
   * <code>COMMAND_START_SHOW_RESP = 11;</code>
   */
  COMMAND_START_SHOW_RESP(11),
  /**
   * <pre>
   *停播请求
   * </pre>
   *
   * <code>COMMAND_END_SHOW_REQ = 12;</code>
   */
  COMMAND_END_SHOW_REQ(12),
  /**
   * <pre>
   *停播通知
   * </pre>
   *
   * <code>COMMAND_END_SHOW_NOTIFY_RESP = 13;</code>
   */
  COMMAND_END_SHOW_NOTIFY_RESP(13),
  /**
   * <pre>
   *心跳请求
   * </pre>
   *
   * <code>COMMAND_HEARTBEAT_REQ = 14;</code>
   */
  COMMAND_HEARTBEAT_REQ(14),
  /**
   * <pre>
   *关闭请求
   * </pre>
   *
   * <code>COMMAND_CLOSE_REQ = 15;</code>
   */
  COMMAND_CLOSE_REQ(15),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>COMMAND_UNKNOW = 0;</code>
   */
  public static final int COMMAND_UNKNOW_VALUE = 0;
  /**
   * <pre>
   *握手请求，含http的websocket握手请求
   * </pre>
   *
   * <code>COMMAND_HANDSHAKE_REQ = 1;</code>
   */
  public static final int COMMAND_HANDSHAKE_REQ_VALUE = 1;
  /**
   * <pre>
   *握手响应，含http的websocket握手响应
   * </pre>
   *
   * <code>COMMAND_HANDSHAKE_RESP = 2;</code>
   */
  public static final int COMMAND_HANDSHAKE_RESP_VALUE = 2;
  /**
   * <pre>
   *鉴权请求
   * </pre>
   *
   * <code>COMMAND_AUTH_REQ = 3;</code>
   */
  public static final int COMMAND_AUTH_REQ_VALUE = 3;
  /**
   * <pre>
   * 鉴权响应
   * </pre>
   *
   * <code>COMMAND_AUTH_RESP = 4;</code>
   */
  public static final int COMMAND_AUTH_RESP_VALUE = 4;
  /**
   * <pre>
   *申请进入群组
   * </pre>
   *
   * <code>COMMAND_JOIN_GROUP_REQ = 5;</code>
   */
  public static final int COMMAND_JOIN_GROUP_REQ_VALUE = 5;
  /**
   * <pre>
   *申请进入群组响应
   * </pre>
   *
   * <code>COMMAND_JOIN_GROUP_RESP = 6;</code>
   */
  public static final int COMMAND_JOIN_GROUP_RESP_VALUE = 6;
  /**
   * <pre>
   *进入房间通知
   * </pre>
   *
   * <code>COMMAND_JOIN_GROUP_NOTIFY_RESP = 7;</code>
   */
  public static final int COMMAND_JOIN_GROUP_NOTIFY_RESP_VALUE = 7;
  /**
   * <pre>
   *聊天请求
   * </pre>
   *
   * <code>COMMAND_CHAT_REQ = 8;</code>
   */
  public static final int COMMAND_CHAT_REQ_VALUE = 8;
  /**
   * <pre>
   *聊天响应
   * </pre>
   *
   * <code>COMMAND_CHAT_RESP = 9;</code>
   */
  public static final int COMMAND_CHAT_RESP_VALUE = 9;
  /**
   * <pre>
   *开播请求
   * </pre>
   *
   * <code>COMMAND_START_SHOW_REQ = 10;</code>
   */
  public static final int COMMAND_START_SHOW_REQ_VALUE = 10;
  /**
   * <pre>
   *开播响应
   * </pre>
   *
   * <code>COMMAND_START_SHOW_RESP = 11;</code>
   */
  public static final int COMMAND_START_SHOW_RESP_VALUE = 11;
  /**
   * <pre>
   *停播请求
   * </pre>
   *
   * <code>COMMAND_END_SHOW_REQ = 12;</code>
   */
  public static final int COMMAND_END_SHOW_REQ_VALUE = 12;
  /**
   * <pre>
   *停播通知
   * </pre>
   *
   * <code>COMMAND_END_SHOW_NOTIFY_RESP = 13;</code>
   */
  public static final int COMMAND_END_SHOW_NOTIFY_RESP_VALUE = 13;
  /**
   * <pre>
   *心跳请求
   * </pre>
   *
   * <code>COMMAND_HEARTBEAT_REQ = 14;</code>
   */
  public static final int COMMAND_HEARTBEAT_REQ_VALUE = 14;
  /**
   * <pre>
   *关闭请求
   * </pre>
   *
   * <code>COMMAND_CLOSE_REQ = 15;</code>
   */
  public static final int COMMAND_CLOSE_REQ_VALUE = 15;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Command valueOf(int value) {
    return forNumber(value);
  }

  public static Command forNumber(int value) {
    switch (value) {
      case 0: return COMMAND_UNKNOW;
      case 1: return COMMAND_HANDSHAKE_REQ;
      case 2: return COMMAND_HANDSHAKE_RESP;
      case 3: return COMMAND_AUTH_REQ;
      case 4: return COMMAND_AUTH_RESP;
      case 5: return COMMAND_JOIN_GROUP_REQ;
      case 6: return COMMAND_JOIN_GROUP_RESP;
      case 7: return COMMAND_JOIN_GROUP_NOTIFY_RESP;
      case 8: return COMMAND_CHAT_REQ;
      case 9: return COMMAND_CHAT_RESP;
      case 10: return COMMAND_START_SHOW_REQ;
      case 11: return COMMAND_START_SHOW_RESP;
      case 12: return COMMAND_END_SHOW_REQ;
      case 13: return COMMAND_END_SHOW_NOTIFY_RESP;
      case 14: return COMMAND_HEARTBEAT_REQ;
      case 15: return COMMAND_CLOSE_REQ;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Command>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Command> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Command>() {
          public Command findValueByNumber(int number) {
            return Command.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.tio.examples.im.common.packets.Chat.getDescriptor().getEnumTypes().get(1);
  }

  private static final Command[] VALUES = values();

  public static Command valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Command(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.tio.examples.im.common.packets.Command)
}

