// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/chat.proto

package org.tio.examples.im.common.packets;

/**
 * <pre>
 **
 * 开始直播响应
 * </pre>
 *
 * Protobuf type {@code org.tio.examples.im.common.packets.BeginToLiveRespBody}
 */
public  final class BeginToLiveRespBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.tio.examples.im.common.packets.BeginToLiveRespBody)
    BeginToLiveRespBodyOrBuilder {
  // Use BeginToLiveRespBody.newBuilder() to construct.
  private BeginToLiveRespBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BeginToLiveRespBody() {
    time_ = 0L;
    liveid_ = 0L;
    rtmppublishurl_ = "";
    rtmpliveurl_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BeginToLiveRespBody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            time_ = input.readInt64();
            break;
          }
          case 16: {

            liveid_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            rtmppublishurl_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            rtmpliveurl_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tio.examples.im.common.packets.Chat.internal_static_com_talent_aio_examples_im_common_packets_BeginToLiveRespBody_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tio.examples.im.common.packets.Chat.internal_static_com_talent_aio_examples_im_common_packets_BeginToLiveRespBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tio.examples.im.common.packets.BeginToLiveRespBody.class, org.tio.examples.im.common.packets.BeginToLiveRespBody.Builder.class);
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private long time_;
  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  public long getTime() {
    return time_;
  }

  public static final int LIVEID_FIELD_NUMBER = 2;
  private long liveid_;
  /**
   * <pre>
   *本次直播id
   * </pre>
   *
   * <code>int64 liveid = 2;</code>
   */
  public long getLiveid() {
    return liveid_;
  }

  public static final int RTMPPUBLISHURL_FIELD_NUMBER = 3;
  private volatile java.lang.Object rtmppublishurl_;
  /**
   * <pre>
   *rtmp推流地址
   * </pre>
   *
   * <code>string rtmppublishurl = 3;</code>
   */
  public java.lang.String getRtmppublishurl() {
    java.lang.Object ref = rtmppublishurl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rtmppublishurl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *rtmp推流地址
   * </pre>
   *
   * <code>string rtmppublishurl = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRtmppublishurlBytes() {
    java.lang.Object ref = rtmppublishurl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rtmppublishurl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RTMPLIVEURL_FIELD_NUMBER = 4;
  private volatile java.lang.Object rtmpliveurl_;
  /**
   * <pre>
   *rtmp播放地址
   * </pre>
   *
   * <code>string rtmpliveurl = 4;</code>
   */
  public java.lang.String getRtmpliveurl() {
    java.lang.Object ref = rtmpliveurl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rtmpliveurl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *rtmp播放地址
   * </pre>
   *
   * <code>string rtmpliveurl = 4;</code>
   */
  public com.google.protobuf.ByteString
      getRtmpliveurlBytes() {
    java.lang.Object ref = rtmpliveurl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rtmpliveurl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0L) {
      output.writeInt64(1, time_);
    }
    if (liveid_ != 0L) {
      output.writeInt64(2, liveid_);
    }
    if (!getRtmppublishurlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, rtmppublishurl_);
    }
    if (!getRtmpliveurlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, rtmpliveurl_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, time_);
    }
    if (liveid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, liveid_);
    }
    if (!getRtmppublishurlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, rtmppublishurl_);
    }
    if (!getRtmpliveurlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, rtmpliveurl_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tio.examples.im.common.packets.BeginToLiveRespBody)) {
      return super.equals(obj);
    }
    org.tio.examples.im.common.packets.BeginToLiveRespBody other = (org.tio.examples.im.common.packets.BeginToLiveRespBody) obj;

    boolean result = true;
    result = result && (getTime()
        == other.getTime());
    result = result && (getLiveid()
        == other.getLiveid());
    result = result && getRtmppublishurl()
        .equals(other.getRtmppublishurl());
    result = result && getRtmpliveurl()
        .equals(other.getRtmpliveurl());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (37 * hash) + LIVEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLiveid());
    hash = (37 * hash) + RTMPPUBLISHURL_FIELD_NUMBER;
    hash = (53 * hash) + getRtmppublishurl().hashCode();
    hash = (37 * hash) + RTMPLIVEURL_FIELD_NUMBER;
    hash = (53 * hash) + getRtmpliveurl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tio.examples.im.common.packets.BeginToLiveRespBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tio.examples.im.common.packets.BeginToLiveRespBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tio.examples.im.common.packets.BeginToLiveRespBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tio.examples.im.common.packets.BeginToLiveRespBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tio.examples.im.common.packets.BeginToLiveRespBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tio.examples.im.common.packets.BeginToLiveRespBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tio.examples.im.common.packets.BeginToLiveRespBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tio.examples.im.common.packets.BeginToLiveRespBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tio.examples.im.common.packets.BeginToLiveRespBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tio.examples.im.common.packets.BeginToLiveRespBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tio.examples.im.common.packets.BeginToLiveRespBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 开始直播响应
   * </pre>
   *
   * Protobuf type {@code org.tio.examples.im.common.packets.BeginToLiveRespBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.tio.examples.im.common.packets.BeginToLiveRespBody)
      org.tio.examples.im.common.packets.BeginToLiveRespBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tio.examples.im.common.packets.Chat.internal_static_com_talent_aio_examples_im_common_packets_BeginToLiveRespBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tio.examples.im.common.packets.Chat.internal_static_com_talent_aio_examples_im_common_packets_BeginToLiveRespBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tio.examples.im.common.packets.BeginToLiveRespBody.class, org.tio.examples.im.common.packets.BeginToLiveRespBody.Builder.class);
    }

    // Construct using org.tio.examples.im.common.packets.BeginToLiveRespBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      time_ = 0L;

      liveid_ = 0L;

      rtmppublishurl_ = "";

      rtmpliveurl_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tio.examples.im.common.packets.Chat.internal_static_com_talent_aio_examples_im_common_packets_BeginToLiveRespBody_descriptor;
    }

    public org.tio.examples.im.common.packets.BeginToLiveRespBody getDefaultInstanceForType() {
      return org.tio.examples.im.common.packets.BeginToLiveRespBody.getDefaultInstance();
    }

    public org.tio.examples.im.common.packets.BeginToLiveRespBody build() {
      org.tio.examples.im.common.packets.BeginToLiveRespBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tio.examples.im.common.packets.BeginToLiveRespBody buildPartial() {
      org.tio.examples.im.common.packets.BeginToLiveRespBody result = new org.tio.examples.im.common.packets.BeginToLiveRespBody(this);
      result.time_ = time_;
      result.liveid_ = liveid_;
      result.rtmppublishurl_ = rtmppublishurl_;
      result.rtmpliveurl_ = rtmpliveurl_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tio.examples.im.common.packets.BeginToLiveRespBody) {
        return mergeFrom((org.tio.examples.im.common.packets.BeginToLiveRespBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tio.examples.im.common.packets.BeginToLiveRespBody other) {
      if (other == org.tio.examples.im.common.packets.BeginToLiveRespBody.getDefaultInstance()) return this;
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (other.getLiveid() != 0L) {
        setLiveid(other.getLiveid());
      }
      if (!other.getRtmppublishurl().isEmpty()) {
        rtmppublishurl_ = other.rtmppublishurl_;
        onChanged();
      }
      if (!other.getRtmpliveurl().isEmpty()) {
        rtmpliveurl_ = other.rtmpliveurl_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tio.examples.im.common.packets.BeginToLiveRespBody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tio.examples.im.common.packets.BeginToLiveRespBody) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long time_ ;
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private long liveid_ ;
    /**
     * <pre>
     *本次直播id
     * </pre>
     *
     * <code>int64 liveid = 2;</code>
     */
    public long getLiveid() {
      return liveid_;
    }
    /**
     * <pre>
     *本次直播id
     * </pre>
     *
     * <code>int64 liveid = 2;</code>
     */
    public Builder setLiveid(long value) {
      
      liveid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *本次直播id
     * </pre>
     *
     * <code>int64 liveid = 2;</code>
     */
    public Builder clearLiveid() {
      
      liveid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object rtmppublishurl_ = "";
    /**
     * <pre>
     *rtmp推流地址
     * </pre>
     *
     * <code>string rtmppublishurl = 3;</code>
     */
    public java.lang.String getRtmppublishurl() {
      java.lang.Object ref = rtmppublishurl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtmppublishurl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *rtmp推流地址
     * </pre>
     *
     * <code>string rtmppublishurl = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRtmppublishurlBytes() {
      java.lang.Object ref = rtmppublishurl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtmppublishurl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *rtmp推流地址
     * </pre>
     *
     * <code>string rtmppublishurl = 3;</code>
     */
    public Builder setRtmppublishurl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rtmppublishurl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *rtmp推流地址
     * </pre>
     *
     * <code>string rtmppublishurl = 3;</code>
     */
    public Builder clearRtmppublishurl() {
      
      rtmppublishurl_ = getDefaultInstance().getRtmppublishurl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *rtmp推流地址
     * </pre>
     *
     * <code>string rtmppublishurl = 3;</code>
     */
    public Builder setRtmppublishurlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rtmppublishurl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object rtmpliveurl_ = "";
    /**
     * <pre>
     *rtmp播放地址
     * </pre>
     *
     * <code>string rtmpliveurl = 4;</code>
     */
    public java.lang.String getRtmpliveurl() {
      java.lang.Object ref = rtmpliveurl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtmpliveurl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *rtmp播放地址
     * </pre>
     *
     * <code>string rtmpliveurl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRtmpliveurlBytes() {
      java.lang.Object ref = rtmpliveurl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtmpliveurl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *rtmp播放地址
     * </pre>
     *
     * <code>string rtmpliveurl = 4;</code>
     */
    public Builder setRtmpliveurl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rtmpliveurl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *rtmp播放地址
     * </pre>
     *
     * <code>string rtmpliveurl = 4;</code>
     */
    public Builder clearRtmpliveurl() {
      
      rtmpliveurl_ = getDefaultInstance().getRtmpliveurl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *rtmp播放地址
     * </pre>
     *
     * <code>string rtmpliveurl = 4;</code>
     */
    public Builder setRtmpliveurlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rtmpliveurl_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.tio.examples.im.common.packets.BeginToLiveRespBody)
  }

  // @@protoc_insertion_point(class_scope:org.tio.examples.im.common.packets.BeginToLiveRespBody)
  private static final org.tio.examples.im.common.packets.BeginToLiveRespBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tio.examples.im.common.packets.BeginToLiveRespBody();
  }

  public static org.tio.examples.im.common.packets.BeginToLiveRespBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BeginToLiveRespBody>
      PARSER = new com.google.protobuf.AbstractParser<BeginToLiveRespBody>() {
    public BeginToLiveRespBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BeginToLiveRespBody(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BeginToLiveRespBody> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BeginToLiveRespBody> getParserForType() {
    return PARSER;
  }

  public org.tio.examples.im.common.packets.BeginToLiveRespBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

